dataset: data/gsm_train.json
model_checkpoint: data/checkpoints/gsm/gsm-coconut
run_id: gsm8k-heuristic-train
max_examples: null
max_new_tokens: 128
num_latent_thoughts: 8
dry_run: false
train_mode: true
live_plot: true
retrieval_threshold: 0.95 # Current intuition - 0.93 same domain, 0.95 same type, 0.98 paraphrase
heuristic_memory: args/gsm_heuristic.yaml
memory_max_entries: 128

# Other 