dataset: data/gsm_train.json
model_checkpoint: data/checkpoints/gsm/gsm-coconut
model_id: openai-community/gpt2
run_id: heuristic_base
max_examples: 15000
max_new_tokens: 128
num_latent_thoughts: 8
dry_run: false
train_mode: true
live_plot: true
live_plot_interactive: false
live_plot_save_every: 100
live_plot_path: plots/heuristic/heuristic_base.png
heuristic_memory: args/gsm_heuristic.yaml
memory_max_entries: 128
retrieval_threshold: 0.95
nudge_min_prob: 0.5
nudge_lr: 0.0003
nudge_inactivity_penalty: 0.2
